### ISSUE TITLE
The use of \xdc is deprecated in USFM 3.0

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#1]
I just observed that there are 6 instances of the marker **\xdc**

Just drawing your attention to the fact that this marker is deprecated in USFM 3.0

**Comment by teusbenschop** [comment]
OK, will remove them, thanks.!

**Comment by DavidHaslam** [comment]
The attached Zip file contains a snapshot of the USFM tag statistics.

[merged.usfm.tags.count.usfm.zip](https://github.com/teusbenschop/ndebele/files/1248280/merged.usfm.tags.count.usfm.zip)

**Comment by teusbenschop** [comment]
There were all in Zechariah 12. They were entered there, years ago, in error, believe. All of them have now been removed.
