### ISSUE TITLE
Xref abbreviation typo in Hosea 10:7

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#10]
**Hosea 10:7** reads:

`\v 7 ISamariya\x + \xt er. 23.13.\x* iqunyiwe\x + \xt Hos. 10.15; 4.5.\x*, \add le\add*nkosi yayo\x + \xt Hos. 3.4; 10.7,15; 11.5; Mika 4.9.\x* injengebazelo\x + \xt Jow. 1.7.\x* ebusweni bamanzi\x + \xt Jobe 24.18.\x*.`

I think the first reference should be \x + \xt Jer. 23.13.\x*

**Comment by teusbenschop** [comment]
Thanks for spotting this "er." book. Yea, probably Jeremiah. Fixed.
