### ISSUE TITLE
Non-localized xref abbreviation in Lamentations 3:54

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#11]
**Lamentations 3:54** reads:

`\v 54 Amanzi\x + \xt Ps 69.2; Jobe 22.11.\x* ageleza phezu kwekhanda lami; ngathi\x + \xt Hlab. 31.22; Lilo 3.18\x*: Ngiqunyiwe\x + \xt Hlab. 31.22; Lilo 3.18.\x*\x + \xt Hlab. 88.5; Hez. 37.11.\x*.`

The first has a non-localized abbreviation for the Ndebele book name for Psalms.

I think it should read `\x + \xt Hlab. 69.2; Jobe 22.11.\x*`

**Comment by teusbenschop** [comment]
Thanks for that. It had slipped through. Yes, "Hlab." is the correct name. Fixed.
