### ISSUE TITLE
Typos found in Lamentations (xref abbreviations)

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#12]
**Lamentations 1:4** reads:
`\v 4 Indlela zeZiyoni ziyalila, ngoba kungekho ozayo emkhosini\x + \xt Lilo. 2.6.\x* omisiweyo; wonke amasango\x + \xt Jer. 14.2.\x* ayo angamanxiwa; abapristi bayo bayabubula\x + \xt Lilo 1.8,11,21,22.\x*, izintombi zayo ezimsulwa zidabukile\x + \xt Zef. 3.18.\x*, layo isekubabeni.`

The full-stop in the first reference is superfluous. It should read \x + \xt Lilo 2.6.\x*

**Lamentations 1:6** reads:
`\v 6 Labo bonke ubuhle bayo busukile kundodakazi yeZiyoni. Iziphathamandla zayo zinjengezindluzele \add e\add*zingatholi idlelo, njalo ziyahamba zingelamandla phambi komzingeli\x + \xt Lilo1.6.\x*.`

There should be a space between `Lilo` and `1.6`

**Lamentations 1:8** reads:
`\v 8 IJerusalema yonile kakhulu, ngakho-ke isingcolile; bonke ababeyihlonipha bayidelela, ngoba sebebonile\x + \xt Hez. 16.37; Jer. 13.22; Hos. 2.10.\x* ubuze bayo; yona isibubula\x + \xt Lilo. 1.4,11.\x*, ibuyele emuva.`

The full-stop in the second reference is superfluous. It should read `\x + \xt Lilo 1.4,11.\x*`

**Lamentations 3:14** reads:
`\v 14 Ngaba yinhlekisa\x + \xt Jer. 20.7.\x* kibo bonke abantu bakithi, ingoma yabo\x + \xt Lilo . 5.14; Jobe 30.9; Lilo 3.63; Hlab. 69.12.\x* usuku lonke.`

The space and full-stop for the first abbreviation in the second xref is superfluous.
It should read `\x + \xt Lilo 5.14; Jobe 30.9; Lilo 3.63; Hlab. 69.12.\x*`

**Comment by teusbenschop** [comment]
Yup, I agree with all proposed changes. Fixed, all of them.
