### ISSUE TITLE
Space missing in xrefs in Hosea 2:3, 2:7 & 2:8

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#13]
**Hosea 2:3** reads:
`\v 3 hlezi ngimhlubule\x + \xt Hez. 16.39.\x* abe nqunu, ngimbeke abe njeng\add o\add*sukw\add ini\x + \xt Hez. 16.4.\x*\add* lokuzalwa kwakhe, ngimenze afanane lenkangala\x + \xt Hez. 19.13; Hos. 2.9.\x*, ngimbeke njengelizwe elomileyo\x + \xt Hez. 19.13; Hos. 2.9.\x*, ngimbulale ngokoma\x + \xt Hez.19.13; Hos. 2.9.\x*\x + \xt Amos 8.13.\x*.`

A space is missing after the first abbeviation in the last xref.

It should read `\x + \xt Hez. 19.13; Hos. 2.9.\x*\x + \xt Amos 8.13.\x*`

**Hosea 2:7** reads:
`\v 7 Alandele izithandwa zakhe\x + \xt Hos. 2.12,13,7,10; Jer. 2.25; Lilo 1.2.\x*, kodwa angazifici; uzazidinga, kodwa anga\add zi\add*tholi. Abesesithi: Ngizahamba\x + \xt Luka 15.17,18.\x* ngibuyele endodeni yami yokuqala\x + \xt Isa. 54.5; Hez. 16.8; Hos.2.19,20.\x*, ngoba\x + \xt Luka 15.17,18.\x* kwakungcono kimi ngalesosikhathi kulakhathesi.`

A space is missing after the third abbeviation in the second xref.

It should read `\x + \xt Isa. 54.5; Hez. 16.8; Hos. 2.19,20.\x*`

**Hosea 2:8** reads:
`\v 8 Ngoba wayengazi\x + \xt Isa. 1.3; Hos.2.20.\x* ukuthi\x + \xt Hez. 16.17-19; 23.41; Hos. 2.5.\x* mina ngamnika amabele\x + \xt Dute. 7.13; 12.17; Neh. 10.39; 13.5,12; Jer. 31.12; Hos. 2.22; Hagg. 1.11; Jow. 1.10; 2.19; Jow. 2.24.\x*, lewayini\x + \xt Hlab. 4.7; Zaga 3.10; Isa. 24.7; 62.8; 65.8,9,22; Hos. 4.11; 7.14; 9.2; Mika 6.15; Zek. 9.17.\x* elitsha, lamafutha\x + \xt Dute. 7.13; 12.17; Neh. 10.39; 13.5,12; Jer. 31.12,22; Hagg. 1.11; Jow. 1.10; 2.19; Jow. 2.24.\x*, ngamandisela isiliva legolide, \add a\add*ba\add li\add*sebenzisela\x + \xt Hos. 8.4; 13.2.\x* uBhali.`

A space is missing after the second abbreviation in the first xref.

It should read `\x + \xt Isa. 1.3; Hos. 2.20.\x*`

**Comment by teusbenschop** [comment]
Thanks for spotting these three missing space! Fixed.
