### ISSUE TITLE
Digit missing in Hosea 4:19 xref 

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#14]
**Hosea 4:19** reads:

`\v 19 Umoya\x + \xt Jer. 4.11,12; 51.1; Isa. 57.13; Hos. 13.15.\x* ubabophele empikweni zawo\x + \xt Hlab. 18.10; 04.3; Zek. 5.9.\x*, njalo bazakuba\x + \xt Isa. 1.29; Jer. 2.26.\x* lenhloni ngenxa yemihlatshelo yabo.`

The second reference in the second xref has a leading zero!
It should probably be `\x + \xt Hlab. 18.10; 104.3; Zek. 5.9.\x*`

**Comment by teusbenschop** [comment]
Yup, "104" I think too. Thanks for spotting it. It was fixed.
