### ISSUE TITLE
Incorrect abbreviations used in 20 xrefs

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#15]
- The abbreviation `Hagg.` is incorrect. It should be `Hag.` with a single `g`. Found in 4 locations.
- The abbreviation `Levi` is incorrect. It should be `Levi.` with a full-stop. Found in 8 locations.
- The abbreviation `Hos` is incorrect. It should be `Hos.` with a full-stop. Found in 8 locations.

_Location details to be supplied_.

**Comment by teusbenschop** [comment]
All locations of "Hagg." were changed to "Hag.".
As for "Levi", it was incorrectly entered in the \toc3. It was changed to \toc3 Levi
All places that has "Hos" were changed to "Hos.".
Thanks for spotting all of these!
