### ISSUE TITLE
Full-stop in xref where comma expected in Hosea 1:7 & Hosea 2:15

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#16]
**Hosea 1:7** reads:
`\v 7 Kodwa ngizayihawukela\x + \xt Hos. 2.23; Zek. 10.6; 2 Kho. 19.35.\x* indlu yakoJuda, ngibasindise ngeN\nd kosi\nd* uNkulunkulu wabo; njalo kangiyikubasindisa\x + \xt Hos. 2.18; Zek. 4.6,9.10; 1 Sam. 17.47.\x* ngedandili, loba ngenkemba, loba ngempi\x + \xt Hos. 2.18; Zek. 4.6,9.10; 1 Sam. 17.47.\x*, ngamabhiza\x + \xt Hos. 2.18; Zek. 4.6,9.10; 1 Sam. 17.47.\x*\x + \xt Hlab. 33.17; Hos. 14.3; Mika 5.10.\x*, kumbe ngabagadi bamabhiza.`

One reference in the last but one xref has a full-stop where a comma is expected.
It should probably be `Zek. 4.6,9,10;`
There is also **no verse text** between the this xref and the last xref.

**Hosea 2:15** reads:
`\v 15 Ngibe sengimnika izivini zakhe\x + \xt Hos. 2.9,12; Hlab. 80.8.\x* kusukela\x + \xt Hlab. 14.5.\x* lapho, lesihotsha\x + \xt Josh. 7.26.\x* seAkori, sibe ngumnyango wethemba. Njalo uzahlabela\x + \xt Nani 21.17.\x* lapho njeng\add e\add*nsuk\add wini\x + \xt Jer. 2.2; Hez. 16.22,60; Hlab. 129.1; Zaga 2.17; Hos. 2.9.10; 11.1.\x*\add* zobutsha bakhe, lanjengosuku\x + \xt Eks. 15.1,20.\x* lokwenyuka kwakhe elizweni leGibhithe.`

One reference in the last but one xref has a full-stop where a comma is expected.
It should probably be `Hos. 2.9,10;`

**Comment by teusbenschop** [comment]
Thanks for spotting these two! Both are OK now after the fix.
