### ISSUE TITLE
Missing digit in one xref found in Hosea 6:2

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#17]
**Hosea 6:2** reads:
`\v 2 Izasivuselela\x + \xt Hlab. 71.20.\x* emva kwensuku ezimbili, ngosuku\x + \xt Luka 24.27,44; Joha. 2.22; 20.9.1; 1 Kor. 15.4.\x* lwesithathu isivuse, njalo siphile phambi kwayo.`

The Johannine reference `20.9.1;` doesn't make sense. I think it should probably be `20.9.10;`

**Comment by teusbenschop** [comment]
Yup, most likely it should be "20.9,10". Fixed. Thanks for spotting it.
