### ISSUE TITLE
Superfluous full-stop before semicolon in 5 xref locations

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#18]
**Lamentations 3:48** reads:
`\v 48 Ilihlo lami\x + \xt Hlab. 119.136; Lilo 1.16.; 2.11; Jer. 9.1.\x* lehlisa imifula yamanzi ngokuchitheka kwendodakazi yabantu bami.`

The full-stop after `Lilo 1:16` is superfluous.

**Lamentations 3:55** reads:
`\v 55 Ngabiza\x + \xt Hlab. 130.1; Jona 2.2.\x* ibizo lakho, N\nd kosi\nd*, ngisemgodini\x + \xt Hlab. 88.6.; Hlab. 63.9.\x* phansi;`

The full-stop after `Hlab. 88.6` is superfluous.

**Lamentations 3:56** reads:
`\v 56 wezwa\x + \xt Hlab. 130.1; Jona 2.2.\x*\x + \xt Hlab. 3.4.; 6.8; 18.6; 66.19; 116.1.\x* ilizwi lami; ungafihli indlebe yakho ekuphefumuleni\x + \xt Eks. 8.15; Esta 4.14.\x* kwami, ekukhaleleni kwami usizo.`

The full-stop after `Hlab. 3.4` is superfluous.

**Hosea 8:5** reads:
`\v 5 Ithole lakho\x + \xt 1 Kho. 12.28.\x*, Samariya\x + \xt Hos. 8.6.; Jer. 23.13.\x*, li\add kw\add*alile\x + \xt Hos. 8.3.\x*; intukuthelo yami iyavutha imelene labo; koze\x + \xt Jer. 13.27.\x* kube nini ukuthi banganelisi ukuba msulwa\x + \xt Gen. 20.5; Hlab. 26.6; 73.13.\x*?`

The full-stop after `Hos. 8.6` is superfluous.

**Hosea 9:13** reads:
`\v 13 UEfrayimi, njengokubona kwami iTire, uhlanyelwe endaweni yokuhlala; kodwa uEfrayimi uzakhuphela\x + \xt Jobe 27.14; Lilo 2.22,16.; Hos. 13.16; Isa. 65.23.\x* abantwana bakhe kumbulali.`

The full-stop after `Lilo 2.22,16` is superfluous. The **verse order** is also suspect.

**Comment by teusbenschop** [comment]
Thanks also for this observation. All locations have been fixed now.
