### ISSUE TITLE
Spurious comma in xref found in Hosea 8:4

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#19]
**Hosea 8:4** reads:
`\v 4 Bona\x + \xt 1 Kho. 12.20; 2 Kho. 15.13,17,23,.\x* babeke amakhosi, kodwa\x + \xt Hos. 7.7; Isa. 54.15.\x* kungengami; bamisa iziphathamandla, kodwa nganginga\add kw\add*azi; \add nge\add*siliva sabo\x + \xt Hos. 2.8; 10.1.\x* legolide labo bazenzela izithombe, ukuze baqunywe.`

The comma before the final full-stop in the first xref is spurious.
It should read `\x + \xt 1 Kho. 12.20; 2 Kho. 15.13,17,23.\x*`

**Comment by teusbenschop** [comment]
All of the places were fixed (there were more) - this one triggered looking for more of the commas before full stop. Thanks for spotting it!
