### ISSUE TITLE
Five cross-reference locations to be reviewed

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#2]
Further to your recent commit, I wondered whether there were any other locations where **\x*** was immediately followed by a letter.

A search for the regexp `\\x\*\w` gave these 5 results.

**Exodus 35**:
> `\v 28 la\x + 30.23.\x*makha\x + 35.8.\x* lamafutha awesibane, lawamafutha okugcoba, lawempepha elephunga elimnandi.`

**Deuteronomy 2**:
> `\v 27 \x + 2.6; Nani 20.17,19.\x*Ake ngidabule elizweni lakho\x + Nani 21.21,22. Hlu. 11.19.\x*; ngizahamba ngomgwaqo kuphela, ngingaphambukeli ngakwesokunene loba ngakwesokhohlo.`

**Joshua 23**:
> `\v 4 Bonani, ngilabele ngenkatho\x + 13.6.\x* lezizizwe eziseleyo zibe yilifa lezizwe zenu, kusukela eJordani, lazo zonke izizwe engiziqumileyo, ngitsho kuze kube selwandle olukhulu \x + 15.12.\x*lapho okutshona khona ilanga.`

**Jeremiah 32**:
> `\v 36 Khathesi-ke, ngakho itsho njalo iN\nd kosi\nd*, uNkulunkulu kaIsrayeli, mayelana lomuzi lo elithi ngawo: Unikelwe esandleni senkosi yeBhabhiloni \x + 32 .24.\x*ngenkemba langendlala langomatshayabhuqe wesifo:\x + 32 .24.\x*`

**2 Timothy 4**:
> `\v 20 UErastu\x + Roma 16.23.\x* wasala eKorinte\x + Seb. 18.1.\x*; kodwa uTrofimu\x + Seb. 20.4.\x* ngamtshiya eMilethu \x + Seb. 20.15,17.\x*egula.`

**Comment by teusbenschop** [comment]
Thanks for spotting these, man! They've been fixed all of them.
