### ISSUE TITLE
7 exceptions to the use of a semicolon to separate references in xrefs

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#20]
The vast majority of xrefs with multiple references use a semicolon to separate them.

Inconsistency: I have found 7 xrefs in which a full-stop is used as the separator.

**Lamentations 1:1** reads:
`\v 1 Yeka\x + \xt Lilo 2.1; 4.1,2; Jer. 8.8; 48.17.\x* ukuhlala kodwa\x + \xt Lilo 3.28.\x* komuzi \add owawu\add*gcwele abantu! Usunjengomfelokazi\x + \xt Isa. 47.9. Jer. 15.8.\x* \add owaw\add*umkhulu phakathi kwezizwe, \add owawuy\add*inkosikazi\x + \xt Lilo 5.16; Ezra 4.20.\x* phakathi kwezabelo\x + \xt Tshu. 2.8.\x* usuyisibhalwa\x + \xt Isa. 31.8.\x*!`

The third xref should be `\x + \xt Isa. 47.9; Jer. 15.8.\x*`

**Lamentations 1:2** reads:
`\v 2 Uyakhala\x + \xt Jer. 9.1.\x* lokukhala inyembezi ebusuku\x + \xt Jobe 7.3. Hlab. 6.6.\x*, lezinyembezi zawo zisezihlathini zawo. Kawulamduduzi\x + \xt Lilo 1.9,16,17,21. Tshu. 4.1.\x* phakathi kwazo zonke izithandwa zawo\x + \xt Jer. 22.22; 30.14,19; Jer. 4.30.\x*. Bonke abangane bawo bawuphethe\x + \xt Isa. 21.2.\x* ngenkohliso, sebeyizitha zawo.`

The second xref should be `\x + \xt Jobe 7.3; Hlab. 6.6.\x*`
The third xref should be `\x + \xt Lilo 1.9,16,17,21; Tshu. 4.1.\x*`

**Lamentations 3:9** reads:
`\v 9 Ibiyele\x + \xt Lilo 3.9. Jobe 19.8; Hos. 2.6; Jobe 3.23.\x* indlela yami ngamatshe abaziweyo, yenza\x + \xt Isa. 24.1.Lilo 3.36; Lilo 3.59; Jobe 19.6.\x* izindlela zami zagoba.`

The first xref should be \x + \xt Lilo 3.9; Jobe 19.8; Hos. 2.6; Jobe 3.23.\x*

**Lamentations 4:17** reads:
`\v 17 Thina\x + \xt Lilo 2.16,17; 3.46-51.\x*, amehlo ethu\x + \xt Hlab. 119.82; Hlab. 123.1-4; Dute. 28.32.\x* asaphela kusizo\x + \xt 2 Kho. 24.7; Isa. 20.5; 30.7. Jer. 37.7; Hez. 29.16.\x* lwethu oluyize; ekulindeleni kwethu salindela isizwe\x + \xt Isa. 30.5,6.\x* \add e\add*singelakusisindisa.`

The third xref should be `\x + \xt 2 Kho. 24.7; Isa. 20.5; 30.7; Jer. 37.7; Hez. 29.16.\x*`

**Hosea 4:12** reads:
`\v 12 Abantu bami babuza\x + \xt Hlu. 18.5; Nani 27.21; Jobe 12.7.\x* esigodweni\x + \xt Jer. 2.27; 3.9. Hab. 2.19.\x* sabo, lentonga yabo\x + \xt Hez. 21.21.\x* izabatshela. Ngoba umoya\x + \xt Hos. 5.4; Isa. 44.20.\x* wokuwula ubaduhisile, ukuze bawule besuka phansi kukaNkulunkulu wabo.`

The third xref should be `\x + \xt Jer. 2.27; 3.9; Hab. 2.19.\x*`

**Hosea 9:6** reads:
`\v 6 Ngoba khangela, bahambile ngenxa yokuchitheka\x + \xt Hos. 7.13.\x*, iGibhithe\x + \xt Hos. 8.13; 11.5,6; 7.16; Jer. 44.11-27.\x* izababutha, iMofi\x + \xt Isa. 19.13.\x* ibangcwabe, \add izindawo\add* zabo eziloyisekayo\x + \xt 1 Kho. 20.6; Hez. 24.16,21,25,16. Jow. 3.5.\x* zesiliva, ukhula oluhlabayo\x + \xt Isa. 34.13; Isa. 32.13; 10.8.\x* luzakudla ilifa lazo, ameva\x + \xt Isa. 34.13; Isa. 32.13; 10.8.\x* abe semathenteni abo.`

The third xref should be `\x + \xt 1 Kho. 20.6; Hez. 24.16,21,25,16; Jow. 3.5.\x*`

**Comment by teusbenschop** [comment]
Yup, it's better to make this consistent. Fixed. Thanks for spotting it.
