### ISSUE TITLE
Unexpected verse order within 7 xref references (1 of which is spurious)

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#21]
**Lamentations 1:22** reads:
\v 22 Kabufike\x + \xt Hlab. 109.15.\x* bonke ububi bazo phambi kwakho, wenze\x + \xt Lilo 2.20,12.\x* kizo njengalokhu wenzile kimi ngenxa yazo zonke iziphambeko zami; ngoba ukububula\x + \xt Lilo 1.4.\x* kwami kunengi, lenhliziyo yami\x + \xt Lilo 5.17; 1.13; Jer. 8.18.\x* iphela amandla.

The verse order in `Lilo 2.20,12.` is unexpected !

**Lamentations 4:6** reads:
`\v 6 Ngoba icala\x + \xt 2 Kho. 7.9; Hlab. 69.27,22; Hez. 14.10; Gen. 4.13; Jobe 21.19.\x*\x + \xt Lilo 4.13,22; 5.7.\x* lendodakazi yabantu bami likhulu\x + \xt Isa. 1.10; Mat. 10.15.\x* kulesono\x + \xt Lilo 3.39.\x* seSodoma, eyachithwa\x + \xt Gen. 19.25; 2 Pet. 2.6; Juda 7.\x* kwangathi ngomzuzwana, kungelazandla ezayonayo.`

The verse order in `Hlab. 69.27,22;` is unexpected !

**Hosea 1:6** reads:
`\v 6 Wasebuya ekhulelwa, wazala indodakazi. \add UNkulunkulu\x + \xt Hos. 1.9,4.\x*\add* wasesithi kuye: Biza ibizo layo \add uthi\add* nguLo-Ruhama\x + \xt Hos. 2.1,23; 1.10; Roma 9.25; 1 Pet. 2.10.\x*, ngoba kangisayikubuya\x + \xt 2 Kho. 17.6,23; Hos 2.4.\x* ngihawukele indlu kaIsrayeli, kodwa\x + \xt Isa. 2.9; Gen. 18.24,26; Eks. 23.21; Josh. 24.19.\x* ngizabasusa lokubasusa.`

The  verse order in `Hos 1.9,4.` is unexpected !

**Hosea 1:9** reads:
`\v 9 \add UNkulunkulu\x + \xt Hos 1.9,4.\x*\add* wasesithi: Biza ibizo layo \add uthi\add* nguLo-Ami\x + \xt Dan. 9.26; Hos. 2.1.\x*; ngoba\x + \xt Hos. 2.23.\x* kalisibo abantu bami, ngakho mina kangisuye owenu.`

The  verse order in `Hos 1.9,4.` is unexpected !

**Hosea 4:17** reads:
`\v 17 UEfrayimi\x + \xt Jer. 7.15; Hos. 5.3.\x* uhlangene lezithombe; myekele\x + \xt Mat. 15.14,4.\x*.`

The  verse order in `Mat. 15.14,4.` is unexpected !

**Hosea 5:3** reads:
`\v 3 Mina\x + \xt Amos 3.2; Hez. 37.16.\x* ngiyamazi uEfrayimi, loIsrayeli kafihlakalanga kimi; ngoba khathesi ufebile, \add wena\add* Efrayimi\x + \xt Hos. 6.10,5; Hez. 23.5; Hos. 4.12,17; 9.1.\x*, uIsrayeli\x + \xt Hos. 6.10,5; Hez. 23.5; Hos. 4.12,17; 9.1.\x* uzingcolisile.`

The verse order in `Hos. 6.10,5;` is unexpected !
The whole xref also occurs twice, so I should think one of these is spurious!

**Comment by teusbenschop** [comment]
Thanks for spotting these places with unexpected verse orders. All of them were not put in the canonical order. As for duplicate xrefs in the verse, it happens plenty of times throughout the Bible. They xrefs were copied from the Cambridge KJV Bible (http://www.ebay.com/bhp/cambridge-bible), and were copied verbatim. Thanks for spotting it!

**Comment by DavidHaslam** [comment]
The eBay link is not to a specific edition of the Cambridge KJV.

CUP has lots of different KJV editions - some as a result of commercial acquisitions over past decades.
Many of them are unchanged from the original publishers, such as Eyre & Spottiswoode.

There has been no attempt by CUP to harmonise all their various KJV editions.
There are minor variations in the text of almost all editions due to this lack of synergy in editing & proofreading.

TBS recommends only one of their KJV editions as a reliable reference work, namely the Concord Reference Bible.

**Comment by teusbenschop** [comment]
Looking in the past order, this one is the one we used: "The New Cambridge Paragraph Bible, with the Apocrypha Black French Morocco Leather : Holy Bible, King James Version"
David Norton; Leather Bound; $75.59. By Amazon.
