### ISSUE TITLE
Insert an \xt marker in each xref (where not already present)

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#23]
Only 824 of the 56943 xrefs in the ndebele data make use of the **\xt** marker.
It would be useful to insert one in each xref.

This would improve the conversion to OSIS XML en route to making a SWORD module.
i.e. It forces the creation of one **reference** element within the cross-reference note.
Though multiple references still have to be split in each note, at least this provides a better starting point.

**Comment by DavidHaslam** [comment]
There are also 18 instances of the **\xk** marker used incorrectly.
These should be changed to the **\xt** marker.

**Comment by DavidHaslam** [comment]
NB. For most of the issues I added yesterday, I was focussed only on the xrefs that already contained **\xt**.
My analysis would therefore be incomplete.

**Comment by teusbenschop** [comment]
All of the superfluous \xt and the erroneous \xk were removed. Thanks for drawing attention to the \xt issue and the \xk errors.
