### ISSUE TITLE
Ambiguous references in Jeremiah 33:17 and 1 John 1:2

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#24]
**Jeremiah 33:17** reads:
`\v 17 Ngoba itsho njalo iN\nd kosi\nd*: Kakuyikuqunywa muntu kuDavida\x + Kho. 2.4. Hlab. 89.4.\x* ohlala esihlalweni sobukhosi sendlu kaIsrayeli.\x + 22.2;33.21.\x*`

The first reference is `Kho. 2.4.` which is ambiguous.

I think it should be `1 Kho. 2.4;` which reads:
`\v 4 ukuze iN\nd kosi\nd* iqinise ilizwi layo eyalikhuluma mayelana lami\x + 2 Sam. 7.25.\x* isithi: Uba amadodana akho eqaphelisa indlela yawo\x + Hlab. 132.12.\x*, ukuhamba ngobuqotho phambi kwami ngenhliziyo yonke yawo langomphefumulo wonke wawo\x + 3.6. 2 Kho. 20.3.\x*, (isithi) kakuyikusweleka\f + \fk kakuyikusweleka: \fl Heb. \fq kakuyikuqunywa.\f* kuwe indoda esihlalweni sobukhosi sikaIsrayeli\x + 2 Sam. 7.12,13.\x*.`

**1 John 1:2** reads:
`\v 2 leMpilo\x + Joha. 14.6. Joha. 1.4.\x* yabonakaliswa\x + Tim. 3.16. 1 Joha. 3.5. Roma 16.26.\x*, sasesi\add yi\add*bona\x + 1.3. Seb. 4.20. 1 Joha. 1.2. Seb. 22.15. Isam. 1.2.\x*, njalo siyafakaza\x + Joha. 15.27; 19.35; 21.24. 1 Joha. 4.14. Luka 24.48.\x* silitshumayeza leyoMpilo elaphakade\x + 5.20.\x*, eyayiloYise\x + Joha. 1.1,2.\x*, yasibonakaliswa kithi\x + 1 Tim. 3.16. 1 Joha. 3.5. Roma 16.26.\x*;`

The first reference in the second xref is `Tim. 3.16.` It should be `1 Tim. 3.16.`
However, the second xref also appears to **duplicate** the last xref in this verse!

**Comment by DavidHaslam** [comment]
Duplicated xrefs in the same verse are quite common in the data.

**Comment by teusbenschop** [comment]
The Cambridge Bible had the duplicates, so do we :)

**Comment by DavidHaslam** [comment]
The two ambiguous references have just been _disambiguated_ in the **Editing** branch of my fork.

I have ignored **duplicated** xrefs.
