### ISSUE TITLE
Two ordinary English words found within xrefs in Micah 6:6,16

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#26]
**Micah 6:6** reads:
`\v 6 Ngizakuza lani\x + Hos. 5.6; Heb. 10.4.\x* phambi kweN\nd kosi\nd*\x + Hlab. 95.2.\x*, ngikhothame phambi\x + Hlab. 57.6.\x* kukaNkulunkulu ophakemeyo\x + Hlab. 92.8. Comp. Isa. 57.15.\x*? Ngizakuza phambi kwayo ngileminikelo yokutshiswa, ngilamathole alomnyaka owodwa yini?`

The fourth xref contains the English abbreviation `Comp.` which should be translated into Ndebele.

**Micah 6:16** reads:
`\v 16 Ngoba izimiso zikaOmri ziyagcinwa\x + 1 Kho. 16.16,25,26; Hos. 5.11.\x*, lawo wonke umsebenzi wendlu kaAhabi\x + 1 Kho. 16.30-33; 21.25,26; 2 Kho. 21.3.\x*, futhi lihamba ngamacebo abo; ukuze ngikwenze ube yincithakalo\x + 7.13. See 2 Kho. 22.19.\x*, labakhileyo bayo babe ngokuncifelwayo\x + 2 Lan. 29.8.\x*; ngokunjalo lizathwala ihlazo labantu bami\x + Isa. 25.8; Jer. 51.51; Lilo 5.1; Hez. 34.29; Hez. 32.24; Dan. 9.16.\x*.`

The third xref contains the English word `See` which should be translated into Ndebele.

**Comment by DavidHaslam** [comment]
In a similar vein, the English abbreviation `ver.` is found in **Jonah 3:8**, which reads:
`\v 8 Kodwa kakuthi umuntu lenyamazana kwembeswe amasaka\x + 1 Kho. 20.31.\x*, bakhale kuNkulunkulu ngamandla, yebo, baphenduke, ngulowo lalowo endleleni yakhe embi\x + Jer. 18.11; 36.3. ver. 10.\x*, lodlakeleni olusezandleni zabo\x + Isa. 59.6.\x*.`

**Comment by teusbenschop** [comment]
The "See" and the "ver", when seen before, they were removed.

**Comment by DavidHaslam** [comment]
In a similar vein, I also observed that the English abbreviation `Heb.` for the _language_ **Hebrew** is found parenthesised in one xref.
`\x + Zek. 3. 2 (Heb.); Juda 23; Jer. 6.29.\x*`

The context is **Amos 4:11** which reads:
`\v 11 Ngachitha \add abanye\add* phakathi kwenu njengalokho uNkulunkulu wachitha iSodoma leGomora\x + Isa. 13.19.\x*, lalinjengesikhuni\x + Zek. 3. 2 (Heb.); Juda 23; Jer. 6.29.\x*\x + Isa. 7.4.\x* esophulwe ekutsheni\x + Zek. 3.2; Juda 23; Jer. 6.29.\x*\x + 3.12.\x*; kanti kaliphendukelanga kimi\x + 4.8-11; Hag. 2.17; Jer. 15.7.\x*, itsho iN\nd kosi\nd*.`


Whenever a _book_ abbreviation matches such an _ordinary_ abbreviation (as sometimes happens for Hebrew & Hebrews), the occurrence is likely to present a _stumbling block_ for conversion scripts such as `usfm2osis.py`.

One way to avoid the clash is to deliberately make the _language_ abbreviation **different**. e.g.
`\x + Zek. 3.2 (Hebr.); Juda 23; Jer. 6.29.\x*`
This ensures that a search for the book abbreviation `Heb.` (with the full-stop) will not match here.

**Comment by teusbenschop** [comment]
I think that the (Hebr.) can be removed, since it refers to the Hebrew language, as you said.

**Comment by DavidHaslam** [comment]
AFAIK, there's no rule in USFM that a cross-reference may not contain additional text.

cf. In OSIS, a cross-reference is merely a specific **type** of the **note** element.

In any case, this is one that I will refrain from implementing.
Better for you to tackle it, but only after I make my pull request, etc.

**Comment by teusbenschop** [comment]
Okay, that's fine.
And after we're done inserting the cross references in the Shona Bible.

**Comment by DavidHaslam** [comment]
Fixes were **not** included yesterday in the recent changes to the **Editing** branch of my fork.
i.e. The words `See` , `Comp.` & `ver.` are still present, as is `(Heb.)`.

**Comment by DavidHaslam** [comment]
When I looked in Jonah 3, which has `ver. 10.` in the xref in verse 8, I also observed that **Jonah 3:10** reads:
`\v 10 UNkulunkulu wasebona imisebenzi yabo, ukuthi baphendukile endleleni yabo embi\x + Jer. 18.11; 36.3; Jona 3.10.\x*\x + Jer. 18.8.\x*; uNkulunkulu wazisola ngobubi ayethe uzabenza kubo, akaze abenza\x + Jer. 18.8.\x*\x + Hlu. 2.18; Amos 7.3.\x*.`

The first xref therein is _self-referential_. It points to `Jona 3.10.` which is the very verse it's in!
It would make more sense to have `Jona 3.8.`

Then we'd have verse 8 with an xref to verse 10 and _vice versa_.

**Comment by DavidHaslam** [comment]
I have just made the required changes in **Amos 4**, **Jonah 3** & **Micah 6**.

**Comment by DavidHaslam** [comment]
Committed the change to the **Editing** branch of my fork.
