### ISSUE TITLE
7 xrefs that start or terminate with unexpected characters

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#27]
**Genesis 46:12** reads:
`\v 12 Lamadodana kaJuda\x + 1 Lan. 2.3; 4.21.\x*: OEri loOnani loShela loPerezi loZera; kodwa uEri wafa, loOnani, elizweni leKhanani\x + 1 Lan. 2.3; 4.21.\x*. Lamadodana kaPerezi ayengoHezironi loHamuli\x + e 38.29. 1 Lan. 2.5.\x*.`

The last xref starts with the unexpected letter `e`

**Isaiah 9:7** reads:
`\v 7 Ukwanda kombuso lokuthula kakuyikuphela\x + 22.23. Hlab. 89.4. Luka 1.32,33.\x*, phezu kwesihlalo sobukhosi sikaDavida\x + 22.23. Hlab. 89.4. Luka 1.32,33.cs\x* laphezu kombuso wakhe, ukuwumisa, lokuwuqinisa ngesahlulelo langokulunga\x + Jer. 23.5.\x*, kusukela khathesi kuze kube nininini. Ukutshiseka kweN\nd kosi\nd* yamabandla\x + 37.32. 2 Kho. 19.31.\x* kuzakwenza lokhu.`

The second xref terminates with the unexpected letters `cs`

**Isaiah 10:24** reads:
`\v 24 Ngakho itsho njalo iNkosi uJehova wamabandla: Bantu bami, elihlala eZiyoni, lingesabi iAsiriya\x + 2 Kho. 19.6.\x* lapho ilitshaya ngenduku\x + 9.4. Jobe 21.9.\x*, iliphakamisela intonga yayo\x + 9.4. Jobe 21.9.\x* njengendlela yamaGibhithe\x + 10.26. Eks. 9.16. 14.30.\x*\x + Gen. 19.31.J\x*.`

The last xref terminates with the unexpected letter `J`

**Isaiah 45:14** reads:
`\v 14 Itsho njalo iN\nd kosi\nd*: Umsebenzi weGibhithe\x + Hlab. 68.31; 72.10,11.\x*, lokuthengiswayo kweEthiyophiya\x + Zef. 3.10.\x* lokwamaShebha\x + Hlab. 72.10.j\x*, amadoda amade\x + 18.2,7; 1 Lan. 11.23.\x*, kuzadlulela kuwe, kuzakuba ngokwakho; bazakulandela, bedlule besemaketaneni\x + Hlab. 149.8.\x*, bakhothame kuwe\x + 49.23.\x*, balabhele kuwe \add besithi\add*: Isibili uNkulunkulu ukuwe\x + 1 Kor. 14.25.\x*, njalo kakho omunye, kakho \add omunye\add* uNkulunkulu\x + 45.5.\x*.`

The third xref terminates with the unexpected letter `j`

_The next two instances involve the **grave accent** which interferes with github markdown._

**Jeremiah 22:3** reads:
`\v 3 Itsho njalo iN\nd kosi\nd*: Yenzani isahlulelo lokulunga,\x + 7.5; 21.12.\x* lophule ophangiweyo esandleni somcindezeli;\x + 7.5; 21.12.\x* lingacindezeli, lingenzi udlakela\x + Levi 19.33.\x* kowezizwe, izintandane, lomfelokazi,\x + Levi 19.33.\x*\x + 7.6. Hlab. 82.3. Isa. 1.17.\x* njalo lingachithi igazi elingelacala kulindawo.\x + 7.6. Hlab. 82.3. Isa. 1.17.\x*\x + 22 .17.`\x*`

The last xref terminates with an unexpected **grave accent**.

**Lamentations 2:17** reads:
`\v 17 IN\nd kosi\nd*\x + Levi 26.16; Dute. 28.15; Lilo 2.8.`\x* yenzile ebikucebile, igcwalisile ilizwi layo eyalilaya kusukela ensukwini\x + Lilo 1.7.\x* zendulo; idilizile\x + Lilo 2.2.\x*, kayihawukelanga\x + Lilo 2.2.\x*; yenzile\x + Hlab. 38.16; 89.42.\x* ukuthi isitha sithokoze phezu kwakho; yaphakamisa uphondo\x + Lilo 2.3.\x* lwabamelene lawe.`

The first xref terminates with an unexpected **grave accent**.

**Daniel 7:7** reads:
`\v 7 Emva kwalokhu ngabona emibonweni yebusuku\x + 7.13; 7.2.\x*, khangela-ke isilo sesine\x + 7.23; 2.40.\x*\x + 7.19,23.\x*, esesabekayo, esethusayo, silamandla kakhulukazi\x + 7.19,23.\x*, silamazinyo amakhulu ensimbi\x + 7.19,23.\x*, sadla\x + 7.19,23.\x* safohloza\x + 7.19,23.\x*, sanyathela okuseleyo ngenyawo zaso\x + 7.19,23.\x*. Njalo sasehlukile kuzo zonke izilo ezazingaphambi kwaso\x + 7.19,23.\x*\x + 7.3.e\x*; futhi sasilempondo ezilitshumi\x + g7.20; Isam. 13.1; 17.12; Isam. 12.3.\x*.`

The last but one xref terminates with the letter `e` and the last xref begins with the letter `g`
Suspect due to the English abbeviation `e.g.` being misprocessed by the editor tool.

**Comment by teusbenschop** [comment]
Whew, what a mess in the Ndebele Bible! I'll have to look at this all after finishing entry of the xrefs in Shona. Thanks man, for digging through this mess!

**Comment by DavidHaslam** [comment]
I can readily fix these in the TextPipe filter I have developed to fix the non-standard abbreviations.
A certain amount of simple pre-processing fixes is already implemented.

**Comment by teusbenschop** [comment]
Fixing them with the text pipe filter, that would be great!

**Comment by DavidHaslam** [comment]
These fixes were included yesterday in the changes to the **Editing** branch of my fork.
