### ISSUE TITLE
6 xrefs that contain a question mark

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#28]
The following 6 xrefs each contain a **question mark**:
```
\x + \xt Jobe 16.12; Jobe 7.20; Hlab. 21.12?; 38.2.\x*
\x + 1 Sam. 19.24. Hez. 1.28; 3.23? Isam. 1.10,17.\x*
\x + 11.8. Gen. 31.49.13.26? Hlu. 10.17. 11.11,29,34. Josh. 15.38; 18.26.\x*
\x + 32.3,34; 33.45,46. Josh. 13.17. Neh. 11.25? Isa. 15.2. Jer. 48.18,22.\x*
\x + 4.48. Josh. 11.3,17. 12.1,5. 13.5,11. Hlab. 42.6. 89.12? 133.3. Ngoma 4.8.\x*
\x + Isa. 8.4; Amos 3.12?; Isa. 17.1.\x*
```
Here are the respective 6 locations:

**Lamentations 3:12** reads:
`\v 12 Igobisile\x + \xt Lilo 2.4.\x* idandili layo, yangimisa\x + \xt Jobe 16.12; Jobe 7.20; Hlab. 21.12?; 38.2.\x* njengento yokunenjwa ngomtshoko.`

**Numbers 24:4** reads:
`\v 4 uthi ozwayo amazwi kaNkulunkulu, obonayo umbono kaSomandla, esiwa, njalo kwembulwe amehlo\x + 1 Sam. 19.24. Hez. 1.28; 3.23? Isam. 1.10,17.\x*.`

**Joshua 11:3** reads:
`\v 3 amaKhanani empumalanga lentshonalanga, lamaAmori lamaHethi lamaPerizi lamaJebusi entabeni\x + 15.63.\x*, lamaHivi\x + Hlu. 3.3. 2 Sam. 24.7.\x* ngaphansi kweHermoni\x + Dute. 3.9.\x* elizweni leMizipa\x + 11.8. Gen. 31.49.13.26? Hlu. 10.17. 11.11,29,34. Josh. 15.38; 18.26.\x*.`

**Numbers 21:30** reads:
`\v 30 Sesibatshokile; iHeshiboni ibhubhile kuze kube seDiboni\x + 32.3,34; 33.45,46. Josh. 13.17. Neh. 11.25? Isa. 15.2. Jer. 48.18,22.\x*; sesibachithile kuze kube seNofa, efika eMedeba\x + Isa. 15.2.\x*.`

**Deuteronomy 3:9** reads:
`\v 9 (AmaSidoni ayibiza iHermoni\x + 4.48. Josh. 11.3,17. 12.1,5. 13.5,11. Hlab. 42.6. 89.12? 133.3. Ngoma 4.8.\x* ngokuthi yiSiriyoni\x + Hlab. 29.6. Dute. 4.48.\x*, lamaAmori ayibiza ngokuthi yiSeniri\x + 1 Lan. 5.23. Ngoma 4.8.\x*.)`

**Amos 1:5** reads:
`\v 5 Njalo ngizakwephula umgoqo\x + Jer. 51.30.\x* weDamaseko\x + Isa. 8.4; Amos 3.12?; Isa. 17.1.\x*, ngiqume umhlali wegceke\x + Gen. 11.2; Hez. 37.1.\x* leAveni\x + Hos. 4.15; 5.8.\x*, lophethe intonga\x + 1.8.\x*, esuka eBeti-Edeni\x + 2 Kho. 19.12.\x*; njalo abantu beSiriya bazathunjelwa eKiri\x + 9.7.\x*\x + 2 Kho. 16.9.\x*, itsho iN\nd kosi\nd*.`

**Comment by DavidHaslam** [comment]
These could only be fixed if I am told what the question marks were for.
It would be easy to just delete them, but that may not be what's required.

**Comment by teusbenschop** [comment]
I think all of them look like errors, and they had no use.

**Comment by DavidHaslam** [comment]
I propose to replace `?;` by `;` and then replace the remaining `?` by `.`

**Comment by teusbenschop** [comment]
Sounds OK

**Comment by DavidHaslam** [comment]
These fixes were included yesterday in the changes to the **Editing** branch of my fork.
