### ISSUE TITLE
6 xrefs that contain a colon

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#29]
The following xrefs contain a **colon**: (the fourth one appears twice)
```
\x + 1 Lan. 2.4,5,6,7,8,9,10,11,12,13,14,15: Mat. 1.3,4,5,6.\x*
\x + 1.14: 2.2,21.\x*
\x + 16:18,21; 12.4.\x*
\x + 2.15. 1 Thes. 5.2: Fil. 4.5.\x*
\x + 26:16.\x*
```
Each of these seems to be a typographical error for either a semicolon or a full-stop.

The respective locations are as follows:

**Ruth 4:18** reads:
`\v 18 Lalezi yizizukulwana zikaPerezi. UPerezi wazala uHezironi\x + 1 Lan. 2.4,5,6,7,8,9,10,11,12,13,14,15: Mat. 1.3,4,5,6.\x*,`

**Haggai 1:1** reads:
`\v 1 Ngomnyaka wesibili kaDariyusi inkosi\x + Ezra 4.24; 5.1; Hag. 1.15; 2.10; Zek. 1.1,7.\x*, ngenyanga yesithupha, ngosuku lokuqala lwenyanga, kwafika ilizwi leN\nd kosi\nd* ngesandla sikaHagayi umprofethi kuZerubhabheli\x + 1 Lan. 3.19.\x* indodana kaSheyalithiyeli\x + 1 Lan. 3.17.\x*, umbusi wakoJuda\x + 1.14: 2.2,21.\x*, lakuJoshuwa indodana\x + Ezra 3.2; Neh. 12.7.\x* kaJehozadaki\x + Ezra 3.2; Neh. 12.7.\x*\x + 1 Lan. 6.15.\x*, umpristi omkhulu, lisithi\x + Zek. 3.1.\x*:`

**Exodus 16:16** reads:
`\v 16 Le yinto iN\nd kosi\nd* elilaye ngayo \add yathi\add*: Ngulowo lalowo kabuthe kuyo okulingene ukudla kwakhe\x + 16:18,21; 12.4.\x*, \w i-omeri\w** ngekhanda, njengenani lemiphefumulo yenu, ngulowo uzathathela abasethenteni lakhe.`

**2 Thessalononians 2:2** reads: (NB. The third and fourth xref are _identical_)
`\v 2 ukuthi lingaphangisi liqhuqhiswe engqondweni, kumbe lethuswe\x + Mat. 24.6. Mark. 13.7.\x*, loba ngumoya\x + 1 Joha. 4.1.\x*, loba yilizwi\x + 2.15. 1 Thes. 5.2: Fil. 4.5.\x*, loba yincwadi\x + 2.15. 1 Thes. 5.2: Fil. 4.5.\x* ngokungathi ivela kithi, ngokungathi usuku lukaKristu selufikile\x + 2 Kor. 1.14.\x*.`

**Proverbs 22:11** reads:
`\v 22 Ulisongo legolide empumulweni yengulube\x + Gen. 24.22.\x* owesifazana obukekayo ophambuka engqondweni\x + 26:16.\x*.`

**Comment by DavidHaslam** [comment]
These corrections are simple enough to be included in my TextPipe filter.

**Comment by teusbenschop** [comment]
Fixing them through the TextPipe filter, that would be great - thanks.

**Comment by DavidHaslam** [comment]
These fixes were included yesterday in the changes to the **Editing** branch of my fork.
