### ISSUE TITLE
xrefs with (mostly) a space before the verse number

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#32]
A search of the counted xrefs for the regexp ` \d+\. \d+\.\D` gave the following 186 hits across 198 locations:
```
002	\x + \xt Zek. 1. 5.\x*
001	\x + 1 Joha. 5. 6.\x*
001	\x + 1 Kho. 5.17. 1 Lan. 22. 2.\x*
001	\x + 1 Kor. 10. 1.\x*
001	\x + 1 Kor. 14.6,26. 2 Kor. 12.1,7. Gal. 1.12; 2. 2.\x*
001	\x + 1 Kor. 15.10. Seb. 9.16. 6. 5. 6. 5.\x*
001	\x + 1 Kor. 15.24. Efe. 5.20. Jak. 1.27; 3.9. 1 Thes. 1. 3.\x*
001	\x + 1 Kor. 3.13. 4. 3. 5.5. 1 Thes. 5.2. 2 Thes. 2.2. Heb. 10.25. 2 Pet. 3.10.\x*
001	\x + 1 Lan. 16.34. Hlab. 78. 105.\x*
001	\x + 1 Lan. 5.1,7,17. 9. 1.\x*
001	\x + 1 Pet. 2.12. Luka 1.68,78. Jobe 10.12. Jer. 6. 6.\x*
002	\x + 1 Pet. 5. 2.\x*
001	\x + 1 Sam. 12. 7.\x*
001	\x + 1 Tim. 1. 6.\x*
001	\x + 1 Tim. 2. 9.\x*
002	\x + 1. 1.\x*
002	\x + 1. 8.\x*
001	\x + 1.8. 11.17. 4.8; 16.5. Heb. 13. 8.\x*
001	\x + 10.18; 24.14. Mark. 6.11; 13. 9. Luka 9.5.\x*
001	\x + 10.19; 14. 17.\x*
001	\x + 10.28. 11.8. Mark. 7. 2.\x*
001	\x + 11.10,23. 8.5. 12.4. 14.6. 17.2,19. 21. 3.\x*
001	\x + 11.23. 18.10. 11. 23. 18. 10.\x*
001	\x + 11.3,7,11. 24.6. 2 Kho. 4.38. Jer. 1.13. Jer. 13. 2.\x*
001	\x + 12. 1.\x*
001	\x + 12.1,10,26. Ezra 2.2,36. 3.2,8. 5.2. Ezra 3. 2.\x*
001	\x + 12.25.15.37,39. Kol. 4.10. 2 Tim. 4.11. Filim. 24. 1 Pet. 5. 1.\x*
001	\x + 12.4,7,9,13,16,17. 13.2,4,11; 16.13; 20.2. Hlab. 91.13. Isa. 27. 1.\x*
001	\x + 13.5. Jer. 14.14,15. Zek. 13. 3.\x*
001	\x + 14. 12.\x*
001	\x + 14. 6.\x*
001	\x + 14.19. Hlab. 28. 1.\x*
001	\x + 14.20. 18. 8.\x*
001	\x + 15.13. 2 Kho. 10.13. 2 Lan. 15.16. Jer. 13.18. 29. 2.\x*
001	\x + 15.3. 21. 2.\x*
001	\x + 16. 6. 22.18,19; 25.33. Hez. 7.11.\x*
001	\x + 16.46,61. 23. 4.\x*
001	\x + 17.4. 1 Kho. 22. 8.\x*
001	\x + 18.16. 2 Kho. 23.10. 2 Lan. 28. 3. Jer. 7.31,32. 19.2,6.\x*
001	\x + 19.19. 24.17. 1 Kho. 8.47. 2 Lan. 6.37. Hlab. 106.6. Jer. 9. 5.\x*
001	\x + 2 Kho. 2. 8.\x*
001	\x + 2 Kho. 24. 8.\x*
001	\x + 2 Kho. 9. 10.\x*
001	\x + 2 Kor. 3. 6.\x*
002	\x + 2 Kor. 8.2. Fil. 2.22. Jak. 1.3,12. 1 Pet. 1. 7.\x*
001	\x + 2 Lan. 16.13. 17. 1.\x*
001	\x + 2 Lan. 19.3. 30.19. Ezra 7.10. Jobe 11.13. Hlab. 78. 8.\x*
001	\x + 2 Lan. 20.21. Hlab. 29.2. Hlab. 110.3. Zaga 14.28. Hlab. 96. 9.\x*
001	\x + 2 Lan. 3.3,4. Hez. 40. 41. 42.\x*
001	\x + 2 Sam. 8. 2.\x*
001	\x + 2. 1.\x*
001	\x + 2. 10. 1 Kor. 5.1.\x*
001	\x + 2. 26.\x*
001	\x + 2. 35. Hez. 17.20; 20.35,36. Mika 6.2.\x*
001	\x + 2. 8.\x*
001	\x + 2.7; 3.2,9;16.18. Ps. 106. 38. Isa. 24.5. Nani 35.33.\x*
002	\x + 20.11,21,22,31,32,40,41,43. 22.2,3,4. 2 Kho. 5.6,7,8. 6. 9.\x*
001	\x + 21. 9.\x*
001	\x + 21.3. Hlab. 149. 6.\x*
001	\x + 22. 24.\x*
001	\x + 22.3. Zek. 7. 9.\x*
001	\x + 23.32. Dute. 7.2. Hlu. 2. 2.\x*
002	\x + 24. 1.\x*
001	\x + 24. 4; 34.13; Levi 26.1; Dute. 7.5; 12. 3; 16.22; 2 Kho. 18.4; 23.14; 2 Lan. 31. 1.\x*
001	\x + 24.6. 24. 6.\x*
001	\x + 24.7; 30.22. 24. 7. 2 Kor. 6.18.\x*
001	\x + 25. 5.\x*
001	\x + 25.46,53. Eks. 1.13,14. Hez. 34. 4.\x*
001	\x + 26. 5.\x*
001	\x + 26.13. 63.7. 66. 3.\x*
001	\x + 27. 11. Gen. 10.18. 1 Lan. 1.16.\x*
001	\x + 27. 4.\x*
001	\x + 28.19. 31.24. Hlab. 45.9. Isa. 13.12. Zaga 25.12. Lilo 4.1. Dan. 10. 5.\x*
001	\x + 28.2. Jobe 8. 2.\x*
001	\x + 29.17. 16.14. 24. 6.\x*
001	\x + 3.1; 4.5; 5.6. 8. 2.\x*
001	\x + 3.12. 14.2. 58. 3.\x*
001	\x + 3.17; Hlab. 2. 6.\x*
001	\x + 3.32. 12.39. Joha. 5. 2.\x*
001	\x + 31. 4.\x*
001	\x + 32. 14.\x*
001	\x + 4. 1.\x*
001	\x + 4.13,22,27; 5.17. Gen. 34. 7.\x*
001	\x + 4.22. 5.8. 2.3,11,13. Roma 11.30. Kol. 1.21; 3.7. Tit. 3. 3. 1 Kor. 6.11; 12.2.\x*
002	\x + 4.5,7. 2. 3.\x*
001	\x + 40. 8.\x*
001	\x + 45. 5.\x*
001	\x + 46. 5.\x*
001	\x + 5. 22. Roma 14.6,8.\x*
001	\x + 5.19,20. 11.38. 27.31. Hlab. 83.6. Gen. 25.12. 2 Sam. 24. 6.\x*
001	\x + 5.26. 4. 1.\x*
001	\x + 57. 5.\x*
001	\x + 6. 6. Roma 12.2. Kol. 1.9. 1 Thes. 4.3.\x*
001	\x + 66.12. Hlab. 34. 5.\x*
001	\x + 7.23-25. 9.18. 10.17. 27.4. Heb. 6. 8.\x*
001	\x + 7.24,25. 7. 4.\x*
001	\x + 7.8. Jer. 49.23-27. Amos 1.3-5. Zek. 9.1. 2 Kho. 16. 9.\x*
001	\x + 8. 1.\x*
002	\x + 8.16. Dan. 12. 4.\x*
001	\x + 8.40. 2 Lan. 14.8. Hlab. 7.13. 11. 2.\x*
002	\x + 8.7. Hlab. 65. 7.\x*
001	\x + 9. 1.\x*
001	\x + 9. 2.\x*
001	\x + 9.26. 2 Kor. 12. 2.\x*
001	\x + 9.32,33. 14.20. 1 Kor. 8.9. 1 Pet. 2. 8.\x*
001	\x + Amos 4.11. Zek. 3. 2.\x*
001	\x + Amos 9. 1.Amos 9. 1\x*
001	\x + Dute. 1.29. 7.21. 20.3. 31. 6.\x*
001	\x + Dute. 9.5. 18.12. Josh. 3.10. Eks. 15. 9.\x*
001	\x + Eks. 12.46. Nani 9.12. Hlab. 34.20. 1 Kor. 5. 7.\x*
001	\x + Eks. 17.2,7. 1 Kor. 10. 9.\x*
001	\x + Eks. 25. 9.\x*
001	\x + Eks. 25.37; 37.23. 2 Lan. 4.20. Zek. 4.2. Isam. 1.13,20; 2.1,5; 11. 4.\x*
001	\x + Eks. 28.8. 39. 5.\x*
001	\x + Eks. 3.6. 6.30. Jer. 1.6. Hlu. 6.22. Luka 5. 8.\x*
001	\x + Eks. 34.6. Hlab. 62.12. 103.8. 111.4. 116.5. 130.7. 145. 8.\x*
001	\x + Eks. 7. 1. 11. 1. Hlab. 105.27-36. Joha. 4.48.\x*
001	\x + Ezra 9. 8.\x*
001	\x + Gal. 2. 4.\x*
001	\x + Gen. 10.11. Hlab. 83. 8.\x*
001	\x + Gen. 2. 4.\x*
001	\x + Gen. 29.32. 30.5. 35.18,22. 46. 8.\x*
001	\x + Gen. 31. 21. Isa. 7.20; 8.7\x*
001	\x + Gen. 32. 2.\x*
001	\x + Gen. 35.4. Hlu. 9. 6.\x*
001	\x + Gen. 36.43.2 Chr. 20. 1.\x*
001	\x + Gen. 4.13. 2 Kho. 7. 9.\x*
001	\x + Gen. 48.21. Dute. 20.1,4; 31. 6.\x*
001	\x + Hez. 47.18; Zek. 14. 8.\x*
001	\x + Hlab. 10. 4.\x*
001	\x + Hlab. 103. 4.\x*
001	\x + Hlab. 111.8. 112. 8.\x*
001	\x + Hlab. 119.176. Mat. 9.36. Mat. 10.6. Luka 15. 4.\x*
001	\x + Hlab. 121. 6.\x*
001	\x + Hlab. 17.6. 31.2. 71.2. 88.2. 102.2. 116. 2.\x*
001	\x + Hlab. 26. 8.\x*
001	\x + Hlab. 3. 3.\x*
001	\x + Hlab. 37.21. Mat. 6. 1.\x*
001	\x + Hlab. 38. 5.\x*
001	\x + Hlab. 57. 142.\x*
001	\x + Hlab. 58. 4.\x*
001	\x + Hlab. 58. 8.\x*
001	\x + Hlab. 68. 9.\x*
001	\x + Hlab. 77. 8.\x*
001	\x + Hlab. 83. 8.\x*
001	\x + Hlu. 5.6. 2 Lan. 15.5. Isa. 33.8. Lilo 1.4. Zek. 7. 14.\x*
001	\x + Hlu. 9. 6.\x*
001	\x + Isa. 1.14; Mal. 1.10; Isa. 1.11; Jer. 7. 2.\x*
001	\x + Isa. 10. 4.\x*
001	\x + Isa. 13. 0.\x*
001	\x + Isa. 2.4. Jow. 3.10. Mika 4. 3.\x*
001	\x + Isa. 3.12; 60.17; Dan. 11.20; Zek. 10. 4.\x*
001	\x + Isa. 35.8; 43.19; 49. 11.\x*
001	\x + Isa. 51.4. Hlab. 49.1. Hlab. 105. 106.\x*
002	\x + Isa. 6. 4.\x*
001	\x + Isa. 9. 1.\x*
002	\x + Jer. 4.8; Mika 1. 8.\x*
001	\x + Jer. 40. 8.\x*
001	\x + Jer. 7.33. Levi 26. 6.\x*
001	\x + Jobe 14. 5.\x*
001	\x + Jobe 14.2. Hlab. 102.11. 144. 4.\x*
001	\x + Joha. 19.40. Mark. 14.8. Joha. 12.7. Gen. 50. 2.\x*
001	\x + Josh. 18. 16. 2. 23.\x*
001	\x + Jow. 2.10. Amos 8. 8.\x*
001	\x + Jow. 3. 4.\x*
001	\x + Levi 26. 4.\x*
001	\x + Levi 26.40. Ezra 9.7. Neh. 1.6. Hlab. 79. 8.\x*
001	\x + Levi 7.12,15; 22. 9. 2 Lan. 33.16. Hlab. 107.22; 116.17.\x*
001	\x + Lilo 4. 4.\x*
001	\x + Luka 14. 7.\x*
001	\x + Luka 15.24,32. Roma 14.9. Isam. 20. 5.\x*
001	\x + Luka 23.50. Mat. 12. 3.\x*
001	\x + Luka 24.30,43. Seb. 1. 4.\x*
001	\x + Mat. 16.1. 19.3. 22.18,35. Mark. 8.11. 10.2. 12.15. Luka 11.16. 20.23. Luka 10.25. Joha. 6. 6.\x*
001	\x + Mat. 4.21. 10. 2.\x*
001	\x + Nani 14. 16. 17.\x*
001	\x + Nani 32.37. Hez. 25. 9.\x*
001	\x + Nani 34.11. Josh. 15.8,10,11. 1 Kho. 6. 8.\x*
001	\x + Neh. 2. 1.\x*
001	\x + Neh. 2.10. Esta 10. 3.\x*
001	\x + Ps 57.4. Isa. 49. 2.\x*
001	\x + Roma 6.3. Gal. 3.27. Seb. 8.16; 19.5. 1 Kor. 1.13; 10. 2.\x*
001	\x + Ruthe 4.11. Gen. 16.2. 30. 3.\x*
001	\x + Seb. 18.14. 2 Kor. 11.1. Efe. 4. 2.\x*
001	\x + Seb. 18.25; 21.21,24. Roma 2.18. 1 Kor. 14.19. Gal. 6. 6.\x*
001	\x + Seb. 2. 4.\x*
```
The majority of these are where there's simply an unexpected space before the verse number.
There are exceptions, however. Here's one example:
`1 Lan. 16.34. Hlab. 78. 105.`
The reference must be to the whole of Psalms 78 and 105, as the former has only 72 verses!
Any attempt at a systematic fix must either _exclude_ or _revert_ such exceptions.

**Comment by DavidHaslam** [comment]
The search results include some xrefs which seem to be due to transcription errors.
One such example is:
`1 Kor. 15.10. Seb. 9.16. 6. 5. 6. 5.`
It's plain that the reference to `6.5.` has been duplicated.

This example is located in **2 Corinthians 11:23** which reads:
`\v 23 Bayizikhonzi zikaKristu yini\x + 3.6.\x*? (Ngikhuluma \add njeng\add*ohlanya) ngiyiso kula\add bo\add*; emisebenzini enzima okwengezelelweyo kakhulu\x + 1 Kor. 15.10. Seb. 9.16. 6. 5. 6. 5.\x*\x + 6.5.\x*, emivimvinyeni\x + 6.5.\x*\x + Seb. 16.23. Mat. 21.35.\x* okwedlula amalawulo, ezintolongweni\x + 6.5.\x*\x + Luka 21.12.\x* okungezelelweyo kakhulu, ezimfeni kanengi\x + Roma 8.36.\x*;`

Observe the further multiple references to `6.5.`

**Comment by DavidHaslam** [comment]
_Further observation:_ 
178 of the hits (192 locations) are at the end of an xref.
These could be fixed systematically, leaving 8 hits (21 locations) to be processed subsequently.

After the systematic fixes, I think that only these two locations require _reverting_.
```
Hlab. 105.106. => Hlab. 105. 106.
Hlab. 78.105. => Hlab. 78. 105.
```

**Comment by DavidHaslam** [comment]
One of the hits is another instance of **duplication** _within_ the same xref.
Originally, it has:
`\x + 11.23. 18.10. 11. 23. 18. 10.\x*`
When corrected by removing the extraneous spaces, it becomes:
`\x + 11.23. 18.10. 11.23. 18.10.\x*`
All that was needed here would be:
`\x + 11.23. 18.10.\x*`

The context for this observation is **Joshua 12:7** which reads:
`\v 7 Lala ngamakhosi elizwe uJoshuwa labantwana bakoIsrayeli abawatshayayo nganeno kweJordani entshonalanga, kusukela eBhali-Gadi esihotsheni seLebhanoni kusiya entabeni yeHalaki\x + 11.17.\x* eyenyukela eSeyiri\x + 11.17.\x*. UJoshuwa walinika-ke izizwe zakoIsrayeli laba yilifa njengokwehlukaniswa kwazo\x + 11.23. 18.10. 11. 23. 18. 10.\x*:`

Observe also that the second and third xrefs `\x + 11.17.\x*` are identical, a further instance of needless duplication.

**Comment by teusbenschop** [comment]
🙈

**Comment by DavidHaslam** [comment]
What should one make of `\x + Nani 14. 16. 17.\x*` ?
Is this a reference to Numbers _chapters_ 14, 16 & 17 ?
Or is it perhaps a reference to **Numbers 14:16,17** ?

My filter currently changes this to `\x + Nani 14. 16.17.\x*` which is wrong for either parsing, so some further tweaks are required.

The context is **Psalm 78:32** which reads:
`\v 32 Kulokhu konke bajinga besona\x + Nani 14. 16. 17.\x*, njalo kabakholwanga ngenxa yezimangaliso zakhe\x + 78.22. Nani 14.11.\x*.`

**Comment by DavidHaslam** [comment]
What should one make of `\x + 2 Lan. 3.3,4. Hez. 40. 41. 42.\x*` ?
Most likely the second reference is to Ezekiel _chapters_ 40 to 42.

The context is **1 Kings 6:2** which reads:
`\v 2 Njalo indlu inkosi uSolomoni eyayakhela uJehova, ubude bayo babuzingalo ezingamatshumi ayisithupha, lobubanzi bayo babungamatshumi amabili, lokuphakama kwayo kwakuzingalo ezingamatshumi amathathu\x + 2 Lan. 3.3,4. Hez. 40. 41. 42.\x*.`

**Comment by DavidHaslam** [comment]
It's almost inevitable that attempts to make _systematic corrections_ by pattern matching will end up with a few **exceptions** that should not have been included.

**Comment by teusbenschop** [comment]
Yes, probably that's the case. Or else to make the systematic corrections, and review each changed cross reference in the commits to see whether it was corrected in a correct way (no pun), or whether to make further updates.

**Comment by DavidHaslam** [comment]
These fixes were included yesterday in the changes to the **Editing** branch of my fork.

A search for the regexp `\d+\. \d+\.\D` now has only these 2 hits:
```
001	\x + 1 Lan. 16.34. Hlab. 78. 105.\x*
001	\x + Isa. 51.4. Hlab. 49.1. Hlab. 105. 106.\x*
```
However, this unintended change to the last xref in **1 Kings 6:2** now requires reverting:
```
001	\x + 2 Lan. 3.3,4. Hez. 40. 41.42.\x*
```
I will leave this issue open as a reminder.

**Comment by teusbenschop** [comment]
I have asked TBS for what to do with the Ndebele cross references, and I do hope that we can use their set, which, I trust, it correct and without errors.

**Comment by DavidHaslam** [comment]
Quite so.

Yet I deemed it appropriate to consolidate my changes, such that, were the existing xrefs still required for whatever reason, we have a better place to continue working from.

If the TBS advice is that we should remove all the xrefs, I can readily implement that with TextPipe.
That may be more efficient than using Bibledit, assuming it doesn't already have a tool to do this.

**Comment by DavidHaslam** [comment]
The change to the last xref in **1 Kings 6:2** has been reverted in the **Editing** branch of my fork.
