### ISSUE TITLE
xrefs without a space after a semicolon

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#33]
A search of the counted xrefs for the regexp `;\S` gave 33 hits over 35 locations:
```
001	\x + 1.50; 8.6;18.2.\x*
001	\x + 12.1-3;13.1-3; 15.1-3.\x*
001	\x + 13.30;14.6,30,38;26.65; 32.12. Dute. 1.36. Josh. 14.6,7,13,14; 15.13-18. Hlu. 1.12-15.\x*
001	\x + 13.30;14.6,30,38;26.65; 32.12. Dute. 1.36. Josh. 14.6,7,13,14; 15.13-18. Hlu. 1.12-15.\x*
002	\x + 14.43,45;13.29.\x*
001	\x + 18.8;26.13,19.\x*
001	\x + 2.11; Isa. 14.1;14.16.\x*
001	\x + 2.11;8.3; Levi 26.12; Isa. 12.6; Hez. 37.26,27; 48.35; Hos. 11.9; Zef. 3.15; 2 Kor. 6.16; Joha. 1.14.\x*
001	\x + 2.11;Hlab. 46.6.\x*
001	\x + 2.19,24;Hos. 2.8.\x*
001	\x + 2.7; 3.2,9;16.18. Ps. 106. 38. Isa. 24.5. Nani 35.33.\x*
001	\x + 20.7;11.44.\x*
001	\x + 22.2;33.21.\x*
001	\x + 3.3;4.10,26.\x*
001	\x + 32.3; 21.25; Dute. 2.24; 3.6. Josh. 13.10. Hlu. 11.26. Neh. 9.22. Ngoma 7.4. Isa. 15.4;16.8,9. Jer. 48.2,34,45.\x*
001	\x + 4.1. Efe. 5.22;6.9.\x*
001	\x + 4.25,32;5.21.\x*
001	\x + 4.31;12.27.\x*
001	\x + 45.17,20; 43.20;Levi 1.4.\x*
001	\x + 8.11;. 12; Zef. 2.7.\x*
001	\x + 8.13;10.6; Amos 9.14,15; Hlab. 107.3; Hez. 37.21.\x*
001	\x + 8.24;8.25.\x*
001	\x + Hlab. 31.18;94.4. Joha. 6.60. Hlab. 139.20. 1 Sam. 2.3.\x*
001	\x + Hlab. 44.13; 79.4;Mika 6.16.\x*
002	\x + Hlab. 47.2;1 Tim. 6.15; Zek. 14.9.\x*
001	\x + Isa. 2.2,3; Mika 4.1;Hez. 40.2.\x*
001	\x + Isa. 34.3; Amos 4.10;Isa. 37.36; 66.24.\x*
001	\x + Jer. 18.15;1 Sam. 2.17; Hez. 22.26; Hez. 44.12.\x*
001	\x + Jobe 1.6. Dan.3.28;\x*
001	\x + Joha. 8.14. Isam. 19.11; 22.6;3.7.\x*
001	\x + Levi 10.11; Dute. 17.9; 2 Lan. 35.3; Jer. 18.18; Zek. 3.7; 7.3; Hez. 7.26;1 Tim. 4.13.\x*
001	\x + Mal. 1.11; Isa. 43.5; 49.12;. Hos. 11.10.\x*
001	\x + Roma 9.20;10.18.\x*
```
This issue can be readily fixed without any side-effects.

**Comment by teusbenschop** [comment]
Automatically fixing them would be a great thing. Thanks for finding them.

**Comment by DavidHaslam** [comment]
Two of the observed hits are `;.` where the full-stop is superfluous.

One of these may warrant further review.
`8.11;. 12; Zef. 2.7.`
Is that a reference to the whole of chapter 12 ?

The location is **Zechariah 8:6** which reads:
`\v 6 Itsho njalo iN\nd kosi\nd* yamabandla: Uba kumangalisa emehlweni ensali yalababantu ngalezozinsuku\x + 8.11;. 12; Zef. 2.7.\x*, kungamangalisa lemehlweni ami yini\x + Gen. 18.14; Mat. 19.26; Roma 4.21.\x*? itsho iN\nd kosi\nd* yamabandla.`

Or might it conceivably be a typo for `8.11,12;` ?

The other hit is more straightforward.
When corrected by removing the superfluous full-stop, it matches another xref exactly.
```
001	\x + Mal. 1.11; Isa. 43.5; 49.12; Hos. 11.10.\x*
001	\x + Mal. 1.11; Isa. 43.5; 49.12;. Hos. 11.10.\x*
```
Even so, this too appears to be an instance of xref **duplication** in the same verse!
**Zechariah 8:7** reads:
`\v 7 Itsho njalo iN\nd kosi\nd* yamabandla: Khangela, ngizasindisa abantu bami\x + 8.13;10.6; Amos 9.14,15; Hlab. 107.3; Hez. 37.21.\x* elizweni lempumalanga\x + Mal. 1.11; Isa. 43.5; 49.12; Hos. 11.10.\x*, lelizweni lokutshona kwelanga\x + Mal. 1.11; Isa. 43.5; 49.12;. Hos. 11.10.\x*;`

Another transcription error? Odd that it occured in the very next verse!

**Comment by teusbenschop** [comment]
Trying to answer the questions, I wish I had a Cambridge Paragraph Bible, so as to find out from there whether it refers to a whole chapter or to a separate verse. I am sorry to not have this Bible.

**Comment by DavidHaslam** [comment]
The **semicolon** fixes were included yesterday in the changes to the **Editing** branch of my fork.

NB. This still leaves the xref in **Zechariah 8:6** in need of review.
