### ISSUE TITLE
xrefs that begin with a number full-stop and space

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#37]
Yet another delinquent pattern has just come to light.

A search within the counted xrefs for the regexp `\+ \d+\. ` gave these 43 hits (over 47 locations)
```
002	\x + 1. 1.\x*
002	\x + 1. 8.\x*
001	\x + 12. 1.\x*
001	\x + 14. 12.\x*
001	\x + 14. 6.\x*
001	\x + 16. 6. 22.18,19; 25.33. Hez. 7.11.\x*
001	\x + 2. 1.\x*
001	\x + 2. 10. 1 Kor. 5.1.\x*
001	\x + 2. 26.\x*
001	\x + 2. 35. Hez. 17.20; 20.35,36. Mika 6.2.\x*
001	\x + 2. 8.\x*
001	\x + 2. Tim. 2.22.\x*
001	\x + 21. 9.\x*
001	\x + 22. 24.\x*
002	\x + 24. 1.\x*
001	\x + 24. 3,8; 29.17.\x*
001	\x + 24. 4; 34.13; Levi 26.1; Dute. 7.5; 12. 3; 16.22; 2 Kho. 18.4; 23.14; 2 Lan. 31. 1.\x*
001	\x + 25. 24; 46.21; 50.37. Hez. 30.5. Eks. 12.38.\x*
001	\x + 25. 5.\x*
001	\x + 26. 5.\x*
001	\x + 27. 11. Gen. 10.18. 1 Lan. 1.16.\x*
002	\x + 27. 14,16.\x*
001	\x + 27. 3,12,20; 28.1.\x*
001	\x + 27. 4.\x*
001	\x + 31. 4.\x*
001	\x + 32. 14.\x*
001	\x + 4. 1.\x*
001	\x + 4. 23,30,35,39,43,47; 8.24. 1 Lan. 23.3,24,27.\x*
001	\x + 40. 8.\x*
001	\x + 45. 5.\x*
001	\x + 46. 5.\x*
001	\x + 49. 13; 51.26.\x*
001	\x + 5. 17; 7.18; 10.17; 17.16; 19.8; 20.17,19. Nani 5.31; 20.20; 9.13.\x*
001	\x + 5. 22. Roma 14.6,8.\x*
001	\x + 5. 23.22. Hlab. 11.4.\x*
001	\x + 5. 29,30.10.28; 18.9; 23.15,33. Mark. 9.43,45,47. Luka 12.5. Jak. 3.6.\x*
001	\x + 57. 5.\x*
001	\x + 6. 15; 8.10,11,12.\x*
001	\x + 6. 6. Roma 12.2. Kol. 1.9. 1 Thes. 4.3.\x*
001	\x + 8. 1.\x*
001	\x + 9. 1.\x*
001	\x + 9. 2 Sam. 8.4. 1 Lan. 18.4. Gen. 49.6.\x*
001	\x + 9. 2.\x*
```
Not all of these are yet fixed by my TextPipe filter.
12 such locations have not been processed.

In addition, there is one malformed xref as follows: `\x + 89.Lilo 2.7.\x*`
This is being changed to `\x + 89. Lilo 2.7.\x*` by the insertion of a space.

The location is **Psalm 89:39** which reads:
`\v 39 Usenze ize isivumelwano senceku yakho\x + 89. Lilo 2.7.\x*; wangcolisa\x + Hlab. 74.7.\x* umqhele wakhe\x + Lilo 5.16.\x* emhlabathini\x + Hlab. 7.5. 89.44. Dan. 8.7.\x*.`

This prompts the question as to what the `89. ` is really for?
It would seem to be a unique instance of an **origin** reference.

**Comment by teusbenschop** [comment]
Whew! There's plenty of work here, never knew it was that bad!

**Comment by DavidHaslam** [comment]
Here are the matching 13 xrefs that remain after running my TextPipe filter:
```
001	\x + 24. 3,8; 29.17.\x*
001	\x + 24. 4; 34.13; Levi 26.1; Dute. 7.5; 12. 3; 16.22; 2 Kho. 18.4; 23.14; 2 Lan. 31.1.\x*
001	\x + 25. 24; 46.21; 50.37. Hez. 30.5. Eks. 12.38.\x*
002	\x + 27. 14,16.\x*
001	\x + 27. 3,12,20; 28.1.\x*
001	\x + 4. 23,30,35,39,43,47; 8.24. 1 Lan. 23.3,24,27.\x*
001	\x + 49. 13; 51.26.\x*
001	\x + 5. 17; 7.18; 10.17; 17.16; 19.8; 20.17,19. Nani 5.31; 20.20; 9.13.\x*
001	\x + 5. 23.22. Hlab. 11.4.\x*
001	\x + 6. 15; 8.10,11,12.\x*
001	\x + 89. Lilo 2.7.\x*
001	\x + 9. 2 Sam. 8.4. 1 Lan. 18.4. Gen. 49.6.\x*
```
The last one is also another **exception** that needs to be reviewed.
The second reference is `2 Sam. 8.4.` so the leading `9.` should not be joined to it.

The location is **Joshua 11:6** which reads:
`\v 6 IN\nd kosi\nd* yasisithi kuJoshuwa: Ungesabi ngenxa yabo, ngoba kusasa phose ngalesisikhathi ngizawanikela wonke esebulewe phambi kukaIsrayeli\x + 10.8.\x*; uzaquma imisipha yamabhiza awo\x + 9. 2 Sam. 8.4. 1 Lan. 18.4. Gen. 49.6.\x*, utshise inqola zawo ngomlilo\x + Dute. 20.1. Josh. 17.16,18. Hlu. 1.19. 4.3.\x*.`

It prompts the question as to what that first reference to `9.` is for?

A regexp that excludes the two exceptions and matches only the other 11 items is `\+ \d+\. \d+[[:punct:]]`

**Comment by DavidHaslam** [comment]
The residual 11 xrefs have just been fixed in the **Editing** branch of my fork.
