### ISSUE TITLE
TBS new address

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#38]
Each book header includes this line as the copyright statement:

`\rem The document is copyrighted (©) 2000-2012 by the Trinitarian Bible Society, Tyndale House, Dorset Road, London, SW19 3NN, England, Registered Charity: 233082 (England), SC038379 (Scotland).`

The address of the TBS new offices is as follows:
`William Tyndale House, 29 Deer Park Road, London, SW19 3NN, England`

It would make sense to review the copyright date range and update the address.

**Comment by teusbenschop** [comment]
If you'd like to make the suggested changes in all 66 books, I can then pull the change request. That would be great.

**Comment by DavidHaslam** [comment]
Do you require the date range to become `2000-2017` ?

**Comment by teusbenschop** [comment]
That range would be okay.

**Comment by DavidHaslam** [comment]
When I get round to doing this, the pull request will include the changes I already committed yesterday that fixed the aberrant book abbreviations, etc. See issue #25

**Comment by DavidHaslam** [comment]
I have just committed the changes in the **Editing** branch of my fork.

**Comment by DavidHaslam** [comment]
Just restored the space before the word **London** in the TBS address.
Corrected a bug in my previously committed changes.

**Comment by teusbenschop** [comment]
That's great, David. Just to be sure, I don't see a pull request, I can rest assured that I've not missed it? :)

**Comment by DavidHaslam** [comment]
My **Editing** branch is now 7 commits ahead of your master. I'll make a pull request in due course.

**Comment by DavidHaslam** [comment]
Did I forget to do this?

When this happens, I wouldn’t mind being reminded by email or message.

**Comment by teusbenschop** [comment]
I forgot about this too. And I can't see how many commits your editing branch is ahead of the master branch. If you make a pull request, I'll review it. Thanks.

**Comment by DavidHaslam** [comment]
teusbenschop:master is up to date with all commits from DavidHaslam:editing.

**Comment by teusbenschop** [comment]
OK!
