### ISSUE TITLE
The acrostic stanza headings in Psalm 119 should use the marker \qa

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#40]
Currently, these 22 headings use the **\d** marker which is defined solely for the canonical Psalm titles.
```
\d ALEPH א
\d BETH ב
\d GIMEL ג
\d DALETH ד
\d HE ה
\d VAU ו
\d ZAIN ז
\d CHETH ח
\d TETH ט
\d JOD י
\d CAPH כ
\d LAMED ל
\d MEM מ
\d NUN נ
\d SAMECH ס
\d AIN ע
\d PE פ
\d TZADDI צ
\d KOPH ק
\d RESH ר
\d SCHIN ש
\d TAU ת
```

In the original Hebrew for Psalm 119, these are not headings.
Rather each of the 8 lines in every stanza begins with the respective Hebrew letter.
In translations such as the English KJV, the translators merely resorted to using headings to denote this feature.

The USFM poetry tag **\qa** is defined for this purpose.
It may still be used even though the **\q** poetry tag is not being used in verse text for this translation.

**Comment by teusbenschop** [comment]
Do you have a fast and quick way to fix those through a filter? If so that would be great! I can then import the pull request. Thank!

**Comment by DavidHaslam** [comment]
It's easy enough to do without using a filter.  Fixed in the **Editing** branch of my fork.
