### ISSUE TITLE
Spurious letter E in Isaiah 1:24 

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#42]
**Isaiah 1:24** contains the letter `E` after the colon & space, and followed by a comma.
`\v 24 Ngakho itsho iNkosi, iN\nd kosi\nd* yamabandla\x + 3.1. 10.33. 19.4. 10.16.\x*, oLamandla wakoIsrayeli\x + Hlab. 132.2.\x*: E, ngizaziduduza ngezitha zami\x + Hez. 5.13.\x*, ngiziphindisele kwabamelana lami\x + Hlu. 16.28. Dute. 32.41.\x*.`

AFAIK, the letter `E` is not a word in the Ndebele dictionary.
_Even on the remote chance that it is, I cannot imagine it appearing on its own between two punctuation marks like this._

**Comment by teusbenschop** [comment]
The letter "E" is a translation for the "Ah" in Hebrew. I also was confused at first, but then after checking with the notes and the other text, it became clear.

**Comment by DavidHaslam** [comment]
The problem is with my lack of imagination. ;>)

`E` is a _hapax legomenon_ in this work.
