### ISSUE TITLE
Almost empty \x ...\x* pair in Acts 5:21

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#8]
**Acts 5:21** reads:

`\v 21 Kwathi sebezwile, bangena ethempelini\x + Joha. 8.2.\x* emadabukakusa, bafundisa\x + \x*. Kodwa kwasekufika umpristi omkhulu\x + 4.5,6.\x* lalabo ababelaye, babizela ndawonye umphakathi\x + 5.27,34,41. Mat. 5.22.\x* labo bonke abadala babantwana bakoIsrayeli, bathumela entolongweni ukubaletha.`

The second pair of xref markers is almost empty, having only the + with no references.

**Comment by teusbenschop** [comment]
Thanks! Fixed.
