### ISSUE TITLE
Incorrectly configured cross-reference in Lamentations 3:24

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/ndebele#9]
**Lamentations 3:24** reads:

`\v 24 IN\nd kosi\nd* iyisabelo sami\x + \xt Hlab. 16.5.\x*, kutsho umphefumulo wami\x + \xt Hlab. 42.5,11; 43.5.\x*; ngakho-ke\x + \xo xt Lilo 3.24.\x* ngizathemba\x + \xt Hlab. 42.5,11; 43.5.\x* kiyo.`

The third xref marker `\x + \xo xt Lilo 3.24.\x*` is incorrectly configured.

Looks like it should just be `\x + \xt Lilo 3.24.\x*` (without the `xo `)

Although `\xo ` is a valid marker for an xref origin, it should never be empty when used.

This is the only instance where `\xo ` is found in the whole data set.

**Comment by teusbenschop** [comment]
Thanks for spotting the " xt " and " xo " mixup!. Fixed.
